import type { ChatConfig } from './types'

const BASE = import.meta.env.BASE_URL

export const config: ChatConfig = {
    header: {
        title: "Hey! My name is Anton",
        font: "Figtree, -apple-system, sans-serif",
        fontSize: 31,
        gif: `${BASE}assets/misc/header.gif`,
        gifSize: 150,
        gifGradient: true,
        gifGradientColor: "rgb(6, 6, 6)",
        gifGradientHeight: 45,
    },
    input: {
        placeholder: 'Say hello or write "contact" to get in touch...',
        font: "Figtree, -apple-system, sans-serif",
        fontSize: 16,
        maxWidth: 768,
        borderRadius: 24,
        streamSpeed: 20,
        mediaMaxWidth: 300,
        mediaGalleryAutoScroll: false,
        mediaGalleryScrollSpeed: 30,
    },
    colors: {
        backgroundColor: "rgb(6, 6, 6)",
        userMessageColor: "rgb(30, 30, 30)",
        userTextColor: "rgb(229, 229, 229)",
        aiBackgroundColor: "rgb(15, 15, 15)",
        aiTextColor: "rgb(212, 212, 212)",
        inputBackgroundColor: "rgb(26, 26, 26)",
        inputBorderColor: "rgb(42, 42, 42)",
        inputTextColor: "rgb(229, 229, 229)",
        buttonColor: "rgb(59, 130, 246)",
        buttonDisabledColor: "rgb(42, 42, 42)",
        quickMessageColor: "rgb(30, 30, 30)",
        quickMessageTextColor: "rgb(212, 212, 212)",
        quickMessageHoverColor: "rgb(42, 42, 42)",
    },
    specialResponses: {
        defaultText: "Hey! If you have any questions or want to get in touch, just write 'contact'. Quick messages will help you navigate.",
        contactFormUrl: "",
        contactFormHeight: 0,
        contactResponseText: "Happy to chat! Drop me an email at hello@antoncreates.cc",
        contactEmail: "hello@antoncreates.cc",
        greetingLottie: `${BASE}assets/misc/greeting-confetti.json`,
        greetingResponseText: 'Hi, glad you\'re here! This portfolio talks back. Pick an option below, or just type "contact" to reach me.',
        helloThereResponseText: "General Kenobi! You are a bold one.",
        helloThereImage: `${BASE}assets/images/hello-there.gif`,
    },
    quickMessages: [
        {
            id: "start",
            text: "Intro",
            verticalContent: false,
            images: [],
            videos: [],
            caption: "I enjoy working at the intersection of different disciplines.\nBy going deep in each area -- from design to AI, AR, and automation. I help clients build solid solutions and connect ideas into systems that actually work.\n\nI see my role as a partner who supports projects from early thinking to real-world execution.\n\nBy nature, I'm a researcher and explorer. I'm a cycling enthusiast with long trips behind me, a lover of mountains, nature, and new experiences -- all of which shape how I think, observe, and build.",
            cards: [],
        },
        {
            id: "design",
            text: "Tell about your design experience",
            verticalContent: false,
            images: [
                `${BASE}assets/images/design-01.webp`,
                `${BASE}assets/images/design-02.webp`,
                `${BASE}assets/images/design-03.webp`,
                `${BASE}assets/images/design-04.webp`,
                `${BASE}assets/images/design-05.webp`,
                `${BASE}assets/images/design-06.webp`,
                `${BASE}assets/images/design-07.webp`,
                `${BASE}assets/images/design-08.webp`,
                `${BASE}assets/images/design-09.webp`,
                `${BASE}assets/images/design-10.webp`,
            ],
            videos: [],
            caption: "I've been creating digital products for over 7 years, working with teams and startups to turn ideas into real, usable solutions. Whether it's an early MVP, improving an existing product, or building a product identity that supports further marketing, I combine skills from multiple areas to deliver meaningful results.",
            cards: [],
        },
        {
            id: "ar",
            text: "How can AR benefit my business?",
            verticalContent: true,
            images: [],
            videos: [
                `${BASE}assets/videos/ar-01.webm`,
                `${BASE}assets/videos/ar-02.webm`,
                `${BASE}assets/videos/ar-03.webm`,
                `${BASE}assets/videos/ar-04.webm`,
                `${BASE}assets/videos/ar-05.webm`,
                `${BASE}assets/videos/ar-06.webm`,
                `${BASE}assets/videos/ar-07.webm`,
                `${BASE}assets/videos/ar-08.webm`,
                `${BASE}assets/videos/ar-09.webm`,
                `${BASE}assets/videos/ar-10.webm`,
            ],
            caption: "Augmented Reality helps your business stand out in a world where attention is short. Instead of just showing your product, AR lets people interact with it -- try it on, explore it, or play with it through Snapchat and TikTok filters or web-based experiences. These interactions feel natural and fun, which leads to higher engagement, more sharing, and stronger brand recall.",
            cards: [],
        },
        {
            id: "ai",
            text: "Automate my work with AI",
            verticalContent: false,
            images: [],
            videos: [
                `${BASE}assets/videos/ai-01.webm`,
                `${BASE}assets/videos/ai-02.webm`,
                `${BASE}assets/videos/ai-03.webm`,
            ],
            caption: "AI can quietly handle the boring parts of your work so you don't have to. I build practical AI tools that run in the background 24/7, automating routine tasks, simplifying workflows, and helping you make faster decisions. The result is less manual work, fewer mistakes, and a serious savings of time and money. Without adding complexity or disrupting how you already work.",
            cards: [],
        },
        {
            id: "projects",
            text: "Any side projects?",
            verticalContent: false,
            images: [],
            videos: [],
            caption: "Yes! Here are a couple of things I've been working on:",
            cards: [
                {
                    url: "https://getmonkey.cc",
                    title: "MonKey",
                    description: "A macOS menu bar utility that auto-corrects keyboard layout mistakes, translates text across 55+ languages, checks grammar, and runs custom AI actions -- all via a hotkey.",
                    image: `${BASE}assets/images/card-monkey.png`,
                },
                {
                    url: "https://simplpear.gumroad.com/l/agentchat",
                    title: "Agent Chat",
                    description: "A lightweight, plug-and-play desktop chat interface that connects directly to your n8n/Make instance. Clean, private, runs locally.",
                    image: `${BASE}assets/images/card-agent-chat.webp`,
                },
            ],
        },
        {
            id: "socials",
            text: "Share your socials",
            verticalContent: false,
            images: [],
            videos: [],
            caption: "Here I publish the results of my work, explorations of new ideas, and insights. Subscribe!",
            cards: [
                {
                    url: "https://www.threads.com/@simplpear",
                    title: "Threads profile",
                    description: "Exploring innovation and sharing experience-driven insights.",
                    image: `${BASE}assets/images/card-threads.png`,
                },
                {
                    url: "https://www.instagram.com/simplpear/",
                    title: "Instagram profile",
                    description: "Anton from Ukraine. Digital design - AR Certified Pro - AI",
                    image: `${BASE}assets/images/card-instagram.png`,
                },
            ],
        },
        {
            id: "human",
            text: "Are you human?",
            verticalContent: false,
            images: [
                `${BASE}assets/images/are-you-human.gif`,
            ],
            videos: [],
            caption: "Beep. Boop. Beep.\nConfirmed: human.\nYou can contact me and we'll figure out how I can help -- no robots involved (yet).",
            cards: [],
        },
        {
            id: "clients",
            text: "Who do you work with?",
            verticalContent: false,
            images: [
                `${BASE}assets/images/clients-01.png`,
                `${BASE}assets/images/clients-02.png`,
                `${BASE}assets/images/clients-03.png`,
                `${BASE}assets/images/clients-04.png`,
                `${BASE}assets/images/clients-05.png`,
            ],
            videos: [],
            caption: "I work with clients around the world -- startups, companies, creatives, non-profits, and individuals who are looking for a partner capable of covering multiple needs. More than 150 projects completed, with about 40% of clients returning. I believe in reliable partnership, honesty, and real passion. If that's how you operate, we should talk!",
            cards: [],
        },
    ],
}
